### ISSUE TITLE
Crashes!

### ISSUE THREAD

**Issue by ImInTheICU** [CheeseOnGithub/cheese-hook#3]
CheeseHook crashes after 10 minutes of use, I'm using Electron and Fluxus!
On electron it sometimes will instant crash no matter what.
This only just started happening after the new update of CheeseHook.

**Comment by CheeseOnGithub** [comment]
combat warriors updated and probably added new anticheat things

i will fix it when electron saveinstance works

**Comment by ImInTheICU** [comment]
Not sure?
Seems like other people are not having problems.

It seems sometimes with Electron it crashes and every 10 minutes with Fluxus.
 
I've been told its a hardware problem but it only happens in CW with only CW scripts.
Also my PC is beefy.

I've debugged a little bit.
And it seems to happen around the anti-cheat bypasser / disabler.


commonly the hook for kick and the getgc()

**Comment by Johnnythescripter** [comment]
Its not the anticheats I played with only lightning util and it still keps freezing or crashing combat warriors probably made a new anticheat or its just executor side since most of the features that he skidded from nova hub are meant for synapse only ;)
![Screenshot 2023-07-09 185432](https://github.com/CheeseOnGithub/cheese-hook/assets/139089348/753cc42b-9db6-4d53-b573-ebc741fb1054)

**Comment by Johnnythescripter** [comment]
i will continue to edit the script ALOT and see if it works if it works i will post the script in here so people could use it

**Comment by ImInTheICU** [comment]
I'm confused?
You say: "Its not the anticheat"

Then later in the sentence you say "Combat warriors probably made a new anticheat"

This makes 0 sense?

Also it seems a-lot of people are starting to have crash problems it seems to be a anticheat problem.

**Comment by Johnnythescripter** [comment]
> 

**THEY DID MAKE NEW ANTICHEATS** ONLY FOR THE **AUTO PARRY THERE WAS A UPDATE**
other wise nothing is new the script is probably synapse only SINCE MAX HUB WORKS you can use that :) THE MODULES USED IN CHEESE HOOK ARE MOSTLY FROM NOVA HUB AND NOVA HUB IS SYNAPSE ONLY NOW. simply just get synapse otherwise the cheats are fucking useless since synapse is down and not selling at the moment

**Comment by Johnnythescripter** [comment]
loadstring(game:HttpGet("https://api.luarmor.net/files/v3/loaders/1d4db6a1b04aaeccf046f7c63fbad31a.lua"))() this is the max hub script it has silent aim and infinite stamina and other features but they work for the non the least so i would reccomend it ok now buh bye

**Comment by Johnnythescripter** [comment]
> I'm confused? You say: "Its not the anticheat"
> 
> Then later in the sentence you say "Combat warriors probably made a new anticheat"
> 
> This makes 0 sense?
> 
> Also it seems a-lot of people are starting to have crash problems it seems to be a anticheat problem.

its also not a anti cheat problem nova hub is discontinued and patched and most of the modules used in cheesehook are from nova hub so the script is bassically fucked its either script side or executor side jmaxxey made his own script hub and it seems to work its just most of the features are behind a pay wall and its kinda trash and laggy :) but still it works so i reccomend using it

for the meantime there will be scripts project hook is already working on it :)
